// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import robot.subsystems.*;

/**
 *
 */
public class auto3BallPickupCmdGrp extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public auto3BallPickupCmdGrp() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        //addParallel (new driveSetLowGearCmd());
        addParallel (new driveSetHighGearCmd());

        addParallel(new flywheelOnHighCmd()); 

        //addParallel(new autoSwingTurretToCenterPosCmd());
        //                shooterRotateToPositionCmd(double position, double speed, boolean brake, double timeout)
        addSequential(new shooterRotateToPositionCmd(          90-25,            0.5,        false,             2));

        // Set hood for High target at 18 feet
        //addSequential(new hoodToPositionCmd(3.465, 5.0));
        addSequential(new hoodToPositionCmd(3.6, 5.0));
        
        // Shoot balls for 5 seconds
        //             shooterFireCmd(int mode, double timeout)
        addSequential (new shooterFireCmd( 1,         4.0));


        // Drop intake to get next balls
        //                  intakeCaptureOnCmd( int mode, double timeout) 
        addParallel (new intakeCaptureOnCmd(       0,            6.0)); // No timeout
        
        // move backwards 12 feet
        //		 		DriveFwd2Cmd		( tgtDist,   Pwr,     Hdg,   Mode,   TO,   Brake, LimitOverideFlag))
        addParallel(new DriveFwd2Cmd		( -244.0,    0.65,    0.0,    0,     6.0,  false,      false));
        //addSequential(new DriveBrakeCmd		(  3.0)); 

        // end capture
        //                  intakeCaptureOffCmd( int mode, double timeout) 
        addSequential (new intakeCaptureOffCmd(       1,            1.0));

        // move forward 4 feet
        //		 		DriveFwd2Cmd		( tgtDist,   Pwr,     Hdg,   Mode,   TO,   Brake, LimitOverideFlag))
        addSequential(new DriveFwd2Cmd		(   54.0,    0.65,    0.0,    0,     4.0,  false,      false));
        //addSequential(new DriveBrakeCmd		(  3.0)); 
        
        // position turret rotate
        //                shooterRotateToPositionCmd(double position, double speed, boolean brake, double timeout)
        addSequential(new shooterRotateToPositionCmd(          90-15,            0.5,        false,             3));

        // position hood for 18 foot shoot
        addSequential(new hoodToPositionCmd(3.6, 5.0));

        // shoot remaing balls
        //             shooterFireCmd(int mode, double timeout)
        addSequential (new shooterFireCmd( 1,         3.0));     

        // Shutoff the flywheel
        addSequential(new flywheelOffCmd()); 
    } 
}
