// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import robot.Robot;

/**
 *
 */
public class hoodToPositionCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_position;
    private double m_timeout;
 
    private double currHoodPos = 0;

    private final double MOVESPEED = 0.3;

    private enum HoodDirState {RAISE, LOWER, DONE};
    private HoodDirState hoodDirState = HoodDirState.DONE;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public hoodToPositionCmd(double position, double timeout) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_position = position;
        m_timeout = timeout;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        setTimeout(m_timeout);
        currHoodPos = Robot.shooterSubSys.getHoodPot();

        System.out.println("Starting hoodToPosCmd tgtPos=" + m_position + "   currentHood Pos=" + currHoodPos );
        if (currHoodPos == m_position) {
            hoodDirState = HoodDirState.DONE;
            System.out.println("State = Done !");
        }

        if (currHoodPos > m_position) {
            hoodDirState = HoodDirState.RAISE;
            System.out.println("State = RAISE !");
            // Raise power = +
        } else {
            hoodDirState = HoodDirState.LOWER;
            System.out.println("State = LOWER !");
            // Lowere power = -
        }
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {

        currHoodPos = Robot.shooterSubSys.getHoodPot();
        System.out.println("Hood to pos CurrPos=" + currHoodPos);

        if (hoodDirState == HoodDirState.RAISE){
            if (currHoodPos > m_position) {
                // Continue Raising 
                //Robot.shooterSubSys.turretHoodMotorSet( MOVESPEED, false);
                Robot.shooterSubSys.turretHoodMotorSet( -MOVESPEED, false);
                return;
            } else {
                // we have reached our target
                System.out.println("State = Done !");
                hoodDirState = HoodDirState.DONE;
                return;
            }
        }

        if (hoodDirState == HoodDirState.LOWER){
            if (currHoodPos < m_position) {
                // Continue Lowereing
                //Robot.shooterSubSys.turretHoodMotorSet( -MOVESPEED, false);
                Robot.shooterSubSys.turretHoodMotorSet( MOVESPEED, false);
                return;
            } else {
                // we have reached our target
                System.out.println("State = Done !");
                hoodDirState = HoodDirState.DONE;
                return;
            }
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if (hoodDirState == HoodDirState.DONE){
            return true;
        }

        if( isTimedOut()){
            System.out.println("hoodToPosCmd has Timed out !!!!!");
            return true;
        }

        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.shooterSubSys.turretHoodMotorStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
