// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import robot.OI;
import robot.Robot;
import robot.subsystems.shooterSubSys;

/**
 *
 */
public class shooterAimByJoystickCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    private double joyTwist = Robot.oi.getcoDriverJoystick().getTwist();
    private double joyThrottle = Robot.oi.getcoDriverJoystick().getThrottle();
    private boolean joyTrigger = Robot.oi.getcoDriverJoystick().getTrigger();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public shooterAimByJoystickCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooterSubSys);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if(joyTrigger == true) {
            if(Robot.shooterSubSys.checkTurretLimitSwitches() == "neither") {
                Robot.shooterSubSys.moveTurret((joyTwist * ((joyThrottle + 1)/2)));
            }

            if(Robot.shooterSubSys.checkTurretLimitSwitches() == "left") {
                if(joyTwist <= 0) {
                    Robot.shooterSubSys.stopTurret();
                } else {
                    Robot.shooterSubSys.moveTurret((joyTwist * ((joyThrottle + 1)/2)));
                }
            }

            if(Robot.shooterSubSys.checkTurretLimitSwitches() == "right") {
                if(joyTwist >= 0) {
                    Robot.shooterSubSys.stopTurret();
                } else {
                    Robot.shooterSubSys.moveTurret((joyTwist * ((joyThrottle + 1)/2)));
                }
            }

            if(Robot.shooterSubSys.checkTurretLimitSwitches() == "both") {
                Robot.shooterSubSys.stopTurret();
            }
            
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if(joyTrigger == false) {
            return true;
        } else {
            return false;
        }
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
